'use client';
import { ChangeEvent, useState } from 'react';
import Link from 'next/link';

type Row = Record<string, string>;
type Issue = { row: number; column: string; value: string; reason: string };
const editable = ['fullName', 'primaryPhone', 'sourceGroup', 'addressLine1', 'country', 'state', 'city', 'postalCode', 'notes', 'whatsappOptedOut'];
const labels: Record<string, string> = { fullName: 'Full Name', primaryPhone: 'Mobile Number', sourceGroup: 'Chapter', addressLine1: 'Address Line 1', country: 'Country', state: 'State', city: 'City', postalCode: 'Postal Code', notes: 'Notes', whatsappOptedOut: 'WhatsApp Opted Out' };

export function ImportClient() {
  const [rows, setRows] = useState<Row[]>([]); const [issues, setIssues] = useState<Issue[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setBusy(true); setMessage(''); const form = new FormData(); form.append('file', file); const response = await fetch('/api/imports', { method: 'PUT', body: form }); const data = await response.json(); setBusy(false); if (!response.ok) { setMessage(data.error || 'Could not read the file.'); return; } setRows(data.rows); setIssues(data.issues); setMessage(data.valid ? 'All rows are valid and ready to import.' : `${data.issues.length} issue(s) need correction.`); }
  async function validateAndImport(commit: boolean) { setBusy(true); setMessage(''); const response = await fetch('/api/imports', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ rows, commit }) }); const data = await response.json(); setBusy(false); if (!response.ok) { setMessage(data.error || 'Import failed.'); return; } if (data.issues?.length) { setIssues(data.issues); setMessage(`${data.issues.length} issue(s) remain. Correct the highlighted fields and validate again.`); return; } if (commit) { setRows([]); setIssues([]); setMessage(`${data.imported} records were imported successfully.`); } else { setIssues([]); setMessage('All rows are valid. You can now import them.'); } }
  const invalidRows = new Set(issues.map((item) => item.row - 2));
  return <main className="min-h-screen bg-bg p-4 sm:p-8"><div className="mx-auto max-w-6xl"><Link href="/admin/dashboard" className="text-sm font-medium text-accent hover:underline">← Dashboard</Link><h1 className="mt-4 text-3xl font-semibold tracking-tight">Import from Excel</h1><p className="mt-2 text-muted">Validate every record before anything is saved. You can correct only the rows with errors here.</p>
  <section className="mt-6 rounded-lg border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold">Prepare your file</h2><ol className="mt-3 list-decimal space-y-1 pl-5 text-sm text-muted"><li>Download the template and keep the first-row column headings unchanged.</li><li><strong>Required:</strong> Full Name (text), Mobile Number (7–15 digits), Chapter (an existing chapter name).</li><li><strong>Optional:</strong> Address Line 1, Country, State, City, Postal Code, Notes, WhatsApp Opted Out.</li><li>Location names must already exist and follow Country → State → City. Use Yes or No for WhatsApp Opted Out.</li><li>Upload up to 2,000 rows and 5 MB. Duplicate mobile numbers are rejected.</li></ol><a href="/api/imports/template" className="mt-4 inline-block rounded-md bg-accent px-4 py-2 text-sm font-medium text-white hover:bg-accent-hover">Download Excel template</a></section>
  <section className="mt-6 rounded-lg border border-border bg-surface p-5"><label className="block text-sm font-medium">Excel file (.xlsx)<input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={upload} disabled={busy} className="mt-2 block w-full text-sm"/></label>{busy && <p className="mt-3 text-sm text-muted">Processing…</p>}{message && <p role="status" className="mt-3 text-sm font-medium">{message}</p>}</section>
  {issues.length > 0 && <section className="mt-6 rounded-lg border border-red-200 bg-red-50 p-5"><h2 className="font-semibold text-red-900">Validation report</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Row</th><th>Column</th><th>Invalid value</th><th>Reason</th></tr></thead><tbody>{issues.map((issue, index) => <tr key={`${issue.row}-${issue.column}-${index}`} className="border-t border-red-100"><td className="py-2">{issue.row}</td><td>{issue.column}</td><td className="font-mono">{issue.value || '—'}</td><td>{issue.reason}</td></tr>)}</tbody></table></div></section>}
  {rows.length > 0 && <section className="mt-6 rounded-lg border border-border bg-surface p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Review and correct</h2><div className="flex gap-2"><button disabled={busy} onClick={() => void validateAndImport(false)} className="rounded-md border border-border px-4 py-2 text-sm font-medium">Validate changes</button><button disabled={busy || issues.length > 0} onClick={() => void validateAndImport(true)} className="rounded-md bg-accent px-4 py-2 text-sm font-medium text-white disabled:opacity-50">Import valid records</button></div></div><p className="mt-2 text-sm text-muted">Highlighted rows contain an issue. Edit the field, then validate again.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="text-xs uppercase text-muted"><tr><th className="p-2">Excel row</th>{editable.map((field) => <th key={field} className="p-2">{labels[field]}</th>)}</tr></thead><tbody>{rows.map((row, rowIndex) => <tr key={rowIndex} className={invalidRows.has(rowIndex) ? 'bg-red-50' : 'border-t border-border'}><td className="p-2 text-muted">{rowIndex + 2}</td>{editable.map((field) => <td key={field} className="p-1"><input value={row[field] || ''} onChange={(event) => setRows((current) => current.map((item, index) => index === rowIndex ? { ...item, [field]: event.target.value } : item))} className="h-9 w-full rounded border border-border bg-white px-2"/></td>)}</tr>)}</tbody></table></div></section>}</div></main>;
}
